version: '3.2'

services:
  postgres:
    container_name: your-cast_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: feed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword123!#
    ports:
      - 5432:5432
    volumes:
      - your-cast-feed:/var/lib/postgresql/data

  zookeeper:
    container_name: your-cast_zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: your-cast_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  your-cast-feed:
    driver: local