server:
  port: 8081

spring:
  application:
    name: your-cast-feed-service
  main:
    banner-mode: off

## Logging setting ##
logging:
  level:
    root: INFO # root level logging
  pattern:
    dateformat: "dd.MM.yyyy HH:mm:ss.SSS" # Set dateformat for logging